### ISSUE TITLE
how to set tool tip text in setup() ?

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxGuiTooltip#1]
I see the tooltips.json file loads in the tooltip texts.
Is there a way to also set these texts in the setup function?

thx.

**Comment by roymacdonald** [comment]
Hi @stephanschulz 
I just added an example for doing such. It is the one called example-inline
Let me know if it works for you.

**Comment by roymacdonald** [comment]
@stephanschulz , I also added another function that makes it easiert to add ofParametes

**Comment by stephanschulz** [comment]
thanks.
this is very helpful.
